### ISSUE TITLE
Kind sparkR doens't exist

### ISSUE THREAD

**Issue by root-ua** [cloudera/livy#24] opened 2016-01-13 16:29 UTC
Please fix typo in file https://github.com/cloudera/livy/blob/master/README.rst#sparkr-example
`data = {'kind': 'sparkR'}`
must be replaced by:
`data = {'kind': 'sparkr'}`

**Comment by ksakellis** [comment] 2016-01-28 18:25
This is a duplicate of: https://issues.cloudera.org/browse/LIVY-12 please track on JIRA

**Closed by ksakellis** 2016-01-28 18:25 UTC
